### ISSUE TITLE
redis.clj bitrot?

### ISSUE THREAD

**Issue by colin-scott** [aphyr/jepsen#19]
Just a heads up, I believe redis/sentinel-app/add should either return `ok` or `error`, but it currently returns a long. This causes the following stacktrace when I try to run redis-sentinel:

```
java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.Associative
        at clojure.lang.RT.assoc(RT.java:703)
        at clojure.core$assoc.invoke(core.clj:187)
        at jepsen.load$wrap_latency$measure_latency__2589.invoke(load.clj:102)
        at jepsen.load$wrap_record_req$record_req__2601.invoke(load.clj:129)
        at jepsen.console$wrap_ordered_log$logger__2560.invoke(console.clj:109)
        at jepsen.load$map_fixed_rate$boss__2582$fn__2584.invoke(load.clj:65)
```

**Comment by bitmonk** [comment]
Well, redis, typically used for caching, can lose some data, the question might be which strategy would lead to losing the least data.  Sentinel provides a reasonable solution to partitions, if 51% or more (more likely 2/3) of your sentinel (not necessarily redis) nodes are available and can talk to each other, though it also can experience a race condition where it loses all data.

I'm considering a combination of twemproxy and sentinel, and we want to be able to test some particular scenarios based on the shape our partitions can take.
