### ISSUE TITLE
jepsen depends on a version of knossos that doesn't exist

### ISSUE THREAD

**Issue by igalic** [aphyr/jepsen#50]
currently, jepsen depends on version 0.2.1-snapshot of knossos, which doesn't exist in clojars (latest is 0.2)
```shell
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % lein deps :tree
Could not find artifact knossos:knossos:jar:0.2.1-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
1 igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] %
```
this seems to have been a very recent addition:
```shell
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % git blame project.clj | grep -i knoss
b3ba335f (Aphyr 2015-02-25 11:45:06 -0800  8)                  [knossos "0.2.1-SNAPSHOT"]
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] %
```
i.e. since b3ba335f

**Comment by aphyr** [comment]
Ah, sorry bout that; I'm actually optimizing and experimenting with knossos in tandem with Jepsen at the moment. New knossos is *much* faster though! Try cloning it from github and running `lein install`.

**Comment by igalic** [comment]
aah! okay! thanks

**Comment by igalic** [comment]
eine leichte verschlimmbesserung:)
```shell
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % ...
igalic@levix ~/src % git clone git@github.com:aphyr/knossos
Cloning into 'knossos'...
remote: Counting objects: 391, done.
remote: Total 391 (delta 0), reused 0 (delta 0), pack-reused 391
Receiving objects: 100% (391/391), 102.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (169/169), done.
Checking connectivity... done.
igalic@levix ~/src % cd knossos
igalic@levix ~/src/knossos (git)-[master] % lein install
Retrieving org/clojure/math.combinatorics/0.0.7/math.combinatorics-0.0.7.pom from central
Retrieving org/clojure/core.typed.rt/0.2.83/core.typed.rt-0.2.83.pom from central
Retrieving org/clojure/core.typed-pom/0.2.83/core.typed-pom-0.2.83.pom from central
Retrieving interval-metrics/interval-metrics/1.0.0/interval-metrics-1.0.0.pom from clojars
Retrieving com/boundary/high-scale-lib/1.0.3/high-scale-lib-1.0.3.pom from boundary-site
Retrieving org/clojure/core.typed.rt/0.2.83/core.typed.rt-0.2.83.jar from central
Retrieving log4j/log4j/1.2.16/log4j-1.2.16.jar from central
Retrieving org/clojure/math.combinatorics/0.0.7/math.combinatorics-0.0.7.jar from central
Retrieving interval-metrics/interval-metrics/1.0.0/interval-metrics-1.0.0.jar from clojars
Retrieving com/boundary/high-scale-lib/1.0.3/high-scale-lib-1.0.3.jar from boundary-site
Created /home/igalic/src/knossos/target/knossos-0.2.1-SNAPSHOT.jar
Wrote /home/igalic/src/knossos/pom.xml
Installed jar and pom into local repo.
igalic@levix ~/src/knossos (git)-[master] % popd
~/src ~/src/jepsen/jepsen ~/src/jepsen ~ ~ ~/Documents/ebooks ~/src/bw/puppet/environments/production ~/src/bw/puppet/environments ~/src/bw/puppet ~/src/bw/puppet/environments/production/modules/kvmhost ~/src/bw/puppet/environments/production/modules/profiles ~/src/bw/puppet/environments/production/modules/stash ~/Downloads ~/src/bw/puppet/environments/production/hieradata ~/src/bw/puppet/environments/production/hierafiles/tlsdata.d ~/src/bw/puppet/environments/production/hierafiles ~/src/bw/puppet/environments/production/modules/kernel ~/src/bw/puppet/puppet-apps ~/src/bw/puppet/production
igalic@levix ~/src % !!
popd
~/src/jepsen/jepsen ~/src/jepsen ~ ~ ~/Documents/ebooks ~/src/bw/puppet/environments/production ~/src/bw/puppet/environments ~/src/bw/puppet ~/src/bw/puppet/environments/production/modules/kvmhost ~/src/bw/puppet/environments/production/modules/profiles ~/src/bw/puppet/environments/production/modules/stash ~/Downloads ~/src/bw/puppet/environments/production/hieradata ~/src/bw/puppet/environments/production/hierafiles/tlsdata.d ~/src/bw/puppet/environments/production/hierafiles ~/src/bw/puppet/environments/production/modules/kernel ~/src/bw/puppet/puppet-apps ~/src/bw/puppet/production
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % lein deps :tree
 [byte-streams "0.1.4"]
 [clj-ssh "0.5.7"]
   [com.jcraft/jsch.agentproxy.core "0.0.6"]
   [com.jcraft/jsch.agentproxy.jsch "0.0.6"]
   [com.jcraft/jsch.agentproxy.pageant "0.0.6"]
   [com.jcraft/jsch.agentproxy.sshagent "0.0.6"]
   [com.jcraft/jsch.agentproxy.usocket-jna "0.0.6"]
     [net.java.dev.jna/jna "3.4.0"]
     [net.java.dev.jna/platform "3.4.0"]
   [com.jcraft/jsch.agentproxy.usocket-nc "0.0.6"]
   [com.jcraft/jsch "0.1.50"]
 [clj-time "0.6.0"]
   [joda-time "2.2"]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [com.netflix.curator/curator-framework "1.3.3" :exclusions [[org.slf4j/slf4j-api] [org.slf4j-log4j12] [com.google.guava/guava]]]
   [com.netflix.curator/curator-client "1.3.3"]
   [org.apache.zookeeper/zookeeper "3.4.5" :exclusions [[com.sun.jmx/jmxri] [javax.jms/jms] [junit] [com.sun.jdmk/jmxtools]]]
     [jline "0.9.94"]
     [org.jboss.netty/netty "3.2.2.Final"]
 [hiccup "1.0.5"]
 [knossos "0.2.1-SNAPSHOT"]
   [com.boundary/high-scale-lib "1.0.3"]
   [interval-metrics "1.0.0"]
   [org.clojure/core.typed.rt "0.2.83"]
   [org.clojure/math.combinatorics "0.0.7"]
   [org.slf4j/slf4j-log4j12 "1.6.1"]
     [log4j "1.2.16"]
     [org.slf4j/slf4j-api "1.6.1"]
   [potemkin "0.3.4"]
     [clj-tuple "0.1.2"]
     [riddley "0.1.6"]
 [myguidingstar/clansi "1.3.0"]
 [org.clojars.achim/multiset "0.1.0-20131122.145427-8"]
   [org.clojure/algo.generic "0.1.1"]
 [org.clojure/clojure "1.6.0"]
 [org.clojure/data.fressian "0.2.0"]
   [org.fressian/fressian "0.6.3"]
 [org.clojure/tools.cli "0.2.2"]
 [org.clojure/tools.logging "0.2.6"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % lein with-profile +elasticsearch test jepsen.system.elasticsearch-test
WARN ignoring checkouts directory knossos as it does not contain a project.clj file.
WARN ignoring checkouts directory elastisch as it does not contain a project.clj file.
WARN ignoring checkouts directory verschlimmbesserung as it does not contain a project.clj file.
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/core/typed/unsafe__init.class or clojure/core/typed/unsafe.clj on classpath: , compiling:(knossos/util.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at knossos.core$eval6079$loading__4958__auto____6080.invoke(core.clj:1)
        at knossos.core$eval6079.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:805)
        at jepsen.core$eval6073$loading__4958__auto____6074.invoke(core.clj:1)
        at jepsen.core$eval6073.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:628)
        at clojure.core$use.doInvoke(core.clj:5618)
        at clojure.lang.RestFn.invoke(RestFn.java:482)
        at jepsen.system.elasticsearch_test$eval182$loading__4958__auto____183.invoke(elasticsearch_test.clj:1)
        at jepsen.system.elasticsearch_test$eval182.invoke(elasticsearch_test.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at user$eval85.invoke(form-init4114477020820919908.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core/typed/unsafe__init.class or clojure/core/typed/unsafe.clj on classpath: 
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at knossos.util$eval8290$loading__4958__auto____8291.invoke(util.clj:1)
        at knossos.util$eval8290.invoke(util.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 99 more
Tests failed.
Error encountered performing task 'test' with profile(s): 'base,system,user,provided,dev,elasticsearch'
Tests failed.
lein with-profile +elasticsearch test jepsen.system.elasticsearch-test  40,06s user 1,89s system 255% cpu 16,401 total
1 igalic@levix ~/src/jepsen/jepsen (git)-[es-1.4] % 
```
i think i'm gonna goto sleep now

**Comment by kaibimouez** [comment]
Hello @mkcp ,
Im using jepsen doing my matser thesis and i see that i have the same error as you when im running ./up.sh (docker).
The error is :
![grafik](https://user-images.githubusercontent.com/10838146/69239052-a8e98700-0b99-11ea-9b7c-cb22b2e7a27d.png).

Thanks for you help
Mouez Kaibi

**Comment by aphyr** [comment]
Hi @kaibimouez. If you're running Jepsen on master, you may have to install dependencies yourself. You can pull the latest knossos source yourself, or check out a version tag instead.

**Comment by kaibimouez** [comment]
Hi @aphyr , i successed now running the 5 containers from n1 to n5 and my first Test in Jepsen ;)
I followed the tutorial of jepsen from Scratch.
Thank you very much
